    System.out.println
                ("Chained exception thrown manually: "+ex1);